global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'notification-system'
    static_configs:
      - targets: ['notification-system:8000']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889'] 